Sitegeist:
  MagicWand:
    # the local flow command
    flowCommand: './flow'
#   # preset which is used by the clone:default command
#   defaultPreset: 'master'
    clonePresets: []
#      # the name of the preset for referencing on the clone:preset command
#      master:
#        # if set to default it is cloneable by calling
#        # './flow clone:preset' without a presetName
#        default: true
#        # hostname or ip of the server to clone from
#        host: ~
#        # ssh username
#        user: ~
#        # ssh port
#        port: ~
#        # ssh options
#        sshOptions: ~
#        # path on the remote server
#        path: ~
#        # flow-context on the remote server
#        context: Production
#        # the flow cli command on the remote server
#        # default is the main flowCommand-Setting
#        flowCommand: ~
#        # commands to execute after cloning
#        postClone:
#         - './flow help'
