Sitegeist:
  MagicWand:

    # the local flow command
    flowCommand: './flow'
#   # preset which is used by the clone:default command
#   defaultPreset: 'master'
    clonePresets: []
#      # the name of the preset for referencing on the clone:preset command
#      master:
#        # hostname or ip of the server to clone from
#        host: ~
#        # ssh username
#        user: ~
#        # ssh port
#        port: ~
#        # ssh options
#        sshOptions: ~
#        # path on the remote server
#        path: ~
#        # flow-context on the remote server
#        context: Production
#        # the flow cli command on the remote server
#        # default is the main flowCommand-Setting
#        flowCommand: ~
#        # commands to execute after cloning
#        postClone:
#         - './flow help'

Neos:
  Flow:
    resource:

      storages:
        magicWandProxyStorage:
          storage: 'Sitegeist\MagicWand\ResourceManagement\Storage\ProxyStorage'
          storageOptions:
            localStorage: defaultPersistentResourcesStorage

      targets:
        magicWandProxyTarget:
          target: 'Sitegeist\MagicWand\ResourceManagement\Target\ProxyTarget'
          targetOptions:
            localTarget: localWebDirectoryPersistentResourcesTarget

      #
      # alter the settings for the persistent collection
      # to use the proxy storage and target instead
      #
      collections:
        persistent:
          storage: 'magicWandProxyStorage'
          target: 'magicWandProxyTarget'

    mvc:
      routes:
        Sitegeist.MagicWand:
          position: 'before Neos.Neos'
